#!/usr/bin/env python3
"""Regenerate checked-in monochrome glyph spans; requires ImageMagick/fonts."""
from pathlib import Path
import subprocess
labels=['BROWSE','PLAY 1','CUE 1','SYNC 1','PLAY 2','CUE 2','SYNC 2','MIXER','SOURCE']
def raster(labels,width=142,height=44,size=20):
 spans=[]
 for index,label in enumerate(labels):
  pixels=subprocess.check_output(['magick','-size',f'{width}x{height}','xc:black','-font','Liberation-Sans','-pointsize',str(size),'-fill','white','-gravity','center','-annotate','0',label,'-depth','8','gray:-'])
  if len(pixels)!=width*height:raise ValueError('Unexpected glyph raster geometry')
  for y in range(height):
   x=0
   while x<width:
    if pixels[y*width+x]<128:x+=1;continue
    start=x
    while x<width and pixels[y*width+x]>=128:x+=1
    spans.append((index*width+start,y,x-start))
 return spans
p=Path(__file__).with_name('native-ui-glyphs.h')
p.write_text('/* Generated by generate-native-labels.py, Liberation Sans20px. */\n'+''.join('static const unsigned short '+name+'[][3]={\n'+''.join('{%d,%d,%d},\n'%s for s in raster(items,width))+'};\n' for name,items,width in [('text_spans',labels,142),('navigation_spans',['SEARCH','TAG LIST','','PLAYER','BACK','SOURCE','INFO'],100),('navigation_tag_add_spans',['','','TAG +'],100),('navigation_tag_remove_spans',['','','TAG -'],100)]))

with p.open('a') as f:
 f.write('static const unsigned short zoom_spans[][3]={\n'+''.join('{%d,%d,%d},\n'%r for r in raster(['ZOOM -','ZOOM +'],90,28,14))+'};\n')
