#!/usr/bin/env python3
"""Regenerate checked-in monochrome glyph spans; requires ImageMagick/fonts."""
from pathlib import Path
import subprocess
labels=['BROWSE','PLAY 1','CUE 1','SYNC 1','PLAY 2','CUE 2','SYNC 2','MIXER','SOURCE']
def raster(labels,width=142):
 spans=[]
 for index,label in enumerate(labels):
  pixels=subprocess.check_output(['magick','-size',f'{width}x44','xc:black','-font','Liberation-Sans','-pointsize','20','-fill','white','-gravity','center','-annotate','0',label,'-depth','8','gray:-'])
  if len(pixels)!=width*44:raise ValueError('Unexpected glyph raster geometry')
  for y in range(44):
   x=0
   while x<width:
    if pixels[y*width+x]<128:x+=1;continue
    start=x
    while x<width and pixels[y*width+x]>=128:x+=1
    spans.append((index*width+start,y,x-start))
 return spans
p=Path(__file__).with_name('native-ui-glyphs.h')
p.write_text('/* Generated by generate-native-labels.py, Liberation Sans20px. */\n'+''.join('static const unsigned short '+name+'[][3]={\n'+''.join('{%d,%d,%d},\n'%s for s in raster(items,width))+'};\n' for name,items,width in [('text_spans',labels,142),('navigation_spans',['PLAYER','BACK','SOURCE','INFO'],100)]))
