#!/usr/bin/env python3
from pathlib import Path
import subprocess
def spans(text,width):
 b=subprocess.check_output(['magick','-size',f'{width}x26','xc:black','-font','Liberation-Sans','-pointsize','15','-fill','white','-gravity','center','-annotate','0',text,'-depth','8','gray:-'])
 result=[]
 for y in range(26):
  x=0
  while x<width:
   if b[y*width+x]<128:x+=1;continue
   start=x
   while x<width and b[y*width+x]>=128:x+=1
   result.append((start,y,x-start))
 return result
allspans=[]
for d in range(2):
 for c,label in enumerate(['HOT CUE','BEAT LOOP','SLIP LOOP','BEAT JUMP']):
  allspans.extend((x+10+640*d+158*c,y,n) for x,y,n in spans(label,132))
Path(__file__).with_name('native-pad-mode-glyphs.h').write_text('/* Generated by generate-pad-mode-labels.py. */\n'+''.join('static const unsigned short '+name+'[][3]={\n'+''.join('{%d,%d,%d},\n'%s for s in rows)+'};\n' for name,rows in [('pad_mode_spans',allspans),('pad_bank_two_spans',spans('2',14))]))
