#!/usr/bin/env python3
"""Regenerate checked-in monochrome glyph spans; requires ImageMagick/fonts."""
from pathlib import Path
import subprocess
labels=['BROWSE','PLAY 1','CUE 1','SYNC 1','PLAY 2','CUE 2','SYNC 2','SOURCE']
spans=[]
for index,label in enumerate(labels):
 pixels=subprocess.check_output(['magick','-size','160x44','xc:black','-font','Liberation-Sans','-pointsize','20','-fill','white','-gravity','center','-annotate','0',label,'-depth','8','gray:-'])
 if len(pixels)!=160*44:raise ValueError('Unexpected glyph raster geometry')
 for y in range(44):
  x=0
  while x<160:
   if pixels[y*160+x]<128:x+=1;continue
   start=x
   while x<160 and pixels[y*160+x]>=128:x+=1
   spans.append((index*160+start,y,x-start))
p=Path(__file__).with_name('native-ui-glyphs.h')
p.write_text('/* Generated by generate-native-labels.py, Liberation Sans20px. */\nstatic const unsigned short text_spans[][3]={\n'+''.join('{%d,%d,%d},\n'%s for s in spans)+'};\n')
